2025-09-11 22:04:16,953 INFO: Aplicação iniciada em modo de debug. [in C:\Users\Pichau\Desktop\zabbix-dashboards\app.py:114]
2025-09-11 22:04:17,681 INFO: Aplicação iniciada em modo de debug. [in C:\Users\Pichau\Desktop\zabbix-dashboards\app.py:114]
2025-09-11 22:04:20,275 INFO: Dashboard acessado, iniciando coleta de dados. [in C:\Users\Pichau\Desktop\zabbix-dashboards\app.py:61]
2025-09-11 22:04:20,907 ERROR: Falha ao buscar dados do Zabbix: 'ZabbixAPIObject' object is not callable [in C:\Users\Pichau\Desktop\zabbix-dashboards\app.py:107]
Traceback (most recent call last):
  File "C:\Users\Pichau\Desktop\zabbix-dashboards\app.py", line 103, in dashboard
    zapi.logout()
TypeError: 'ZabbixAPIObject' object is not callable
2025-09-11 22:05:20,986 INFO: Dashboard acessado, iniciando coleta de dados. [in C:\Users\Pichau\Desktop\zabbix-dashboards\app.py:61]
2025-09-11 22:05:21,679 ERROR: Falha ao buscar dados do Zabbix: 'ZabbixAPIObject' object is not callable [in C:\Users\Pichau\Desktop\zabbix-dashboards\app.py:107]
Traceback (most recent call last):
  File "C:\Users\Pichau\Desktop\zabbix-dashboards\app.py", line 103, in dashboard
    zapi.logout()
TypeError: 'ZabbixAPIObject' object is not callable
2025-09-11 22:05:23,588 INFO: Aplicação iniciada em modo de debug. [in C:\Users\Pichau\Desktop\zabbix-dashboards\app.py:114]
